In [1]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [4]:
np.array(l)

array([1, 2, 3, 4])

In [5]:
arr=np.array(l)
type(arr)

numpy.ndarray

In [8]:
#one dimensional array
arr.ndim

1

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#2 dimensional array
arr1=np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [10]:
np.matrix(l)#convert 2 dimensional array

matrix([[1, 2, 3, 4]])

In [13]:
mat=np.matrix(l)

In [11]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [15]:
np.asanyarray(mat)#it does not convert into any array because matrix is subclass of
#array default matrix is array

matrix([[1, 2, 3, 4]])

In [17]:
#shallow copy
a=arr

In [18]:
a

array([1, 2, 3, 4])

In [19]:
arr[0]=100

In [20]:
arr

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [23]:
#deep copy
b=np.copy(arr)

In [24]:
b

array([100,   2,   3,   4])

In [25]:
b[0]=200

In [26]:
b

array([200,   2,   3,   4])

In [27]:
arr

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
list((i*i for i in range(5)))

[0, 1, 4, 9, 16]

In [32]:
iterable=(i*i for i in range(5))

In [34]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring('23,24,25,26', sep=',')

array([23., 24., 25., 26.])

In [37]:
np.fromstring('23 24 25 26', sep=' ')

array([23., 24., 25., 26.])

In [38]:
#to check dimension
arr.ndim

1

In [39]:
arr1.ndim

2

In [40]:
#to check the number of elements
arr.size

4

In [41]:
arr.size

4

In [42]:
#it tells the matrix shape which means number of rows and columns
arr.shape

(4,)

In [43]:
arr1.shape

(2, 3)

In [45]:
#to check the data types
arr.dtype

dtype('int64')

In [46]:
arr1.dtype

dtype('int64')

In [47]:
#numpy part2

In [48]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
np.arange(.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [51]:
list(np.arange(.4,10.4))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [52]:
list(np.arange(.4,10.4,0.5))

[0.4,
 0.9,
 1.4,
 1.9,
 2.4,
 2.9,
 3.4,
 3.9,
 4.4,
 4.9,
 5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9]

In [54]:
np.linspace(1,8, 4)

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [55]:
np.linspace(1,8, 20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [57]:
np.logspace(1,10,20)

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [58]:
#we can change the base default is base 10
np.logspace(1,10,20,base=2)

array([   2.        ,    2.77730229,    3.85670399,    5.3556164 ,
          7.43708284,   10.32751358,   14.34131354,   19.91508143,
         27.65510059,   38.40328703,   53.32876841,   74.05505519,
        102.836637  ,  142.80421347,  198.30523421,  275.37679007,
        382.40229418,  531.02338276,  737.40622722, 1024.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
#3 rows and 5 columns
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
#generate 3d array with 4 rows and 2 columns
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
np.zeros((3,4,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [11]:
#generate ones with six column
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
arr=np.ones((2,3))

In [11]:
arr+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [12]:
arr*7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [17]:
#empty will create any same values with given shape
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.empty((2,3))

array([[7., 7., 7.],
       [7., 7., 7.]])

In [19]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#conversion of nd-array to dataframe
a=np.eye(4)
import pandas as pd
pd.DataFrame(a)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [7]:
#when we want generate random numbers with given shape
np.random.rand(2,3)

array([[0.5959389 , 0.59696942, 0.23320744],
       [0.32713205, 0.51254186, 0.19228114]])

In [26]:
#the diffference between rand and randn is rand produces any meand and standard deviation but randn produces mean 0 and standard deviation 1
np.random.randn(2,3)

array([[-1.71536055,  0.67357754,  0.97085467],
       [ 0.84647227,  0.14041716,  1.56437195]])

In [27]:
#when we want to generate random integers with integers in between 1 to 8 with given shape
np.random.randint(1,8,(3,4))

array([[7, 4, 3, 5],
       [6, 3, 2, 2],
       [1, 6, 3, 3]])

In [28]:
a2=np.random.randint(1,8,(3,4))
a2.size

12

In [29]:
#when we want to get a shape
a2.shape

(3, 4)

In [30]:
#if we want to reshape the given shape we use reshape function in that matrix m*n should greater of new reshape values
#suppoose we have 3*4 matrix its size hold 12 elements we have to reshape matrix such way that new m*n==12
a2.reshape(6,2)

array([[3, 3],
       [2, 2],
       [6, 3],
       [6, 2],
       [1, 2],
       [4, 7]])

In [31]:
a2.reshape(2,6)

array([[3, 3, 2, 2, 6, 3],
       [6, 2, 1, 2, 4, 7]])

In [32]:
a2.reshape(4,3)

array([[3, 3, 2],
       [2, 6, 3],
       [6, 2, 1],
       [2, 4, 7]])

In [33]:
a2.reshape(4,-1)

array([[3, 3, 2],
       [2, 6, 3],
       [6, 2, 1],
       [2, 4, 7]])

In [34]:
a2.reshape(-1,4)

array([[3, 3, 2, 2],
       [6, 3, 6, 2],
       [1, 2, 4, 7]])

In [35]:
a2.reshape(2,2,3)

array([[[3, 3, 2],
        [2, 6, 3]],

       [[6, 2, 1],
        [2, 4, 7]]])

In [36]:
a2.reshape(2,2,3,1,1,1,1)

array([[[[[[[3]]]],



         [[[[3]]]],



         [[[[2]]]]],




        [[[[[2]]]],



         [[[[6]]]],



         [[[[3]]]]]],





       [[[[[[6]]]],



         [[[[2]]]],



         [[[[1]]]]],




        [[[[[2]]]],



         [[[[4]]]],



         [[[[7]]]]]]])

In [37]:
a3=np.random.randint(1,8,(5,7))

In [38]:
a3

array([[4, 4, 6, 6, 3, 7, 1],
       [3, 6, 1, 3, 5, 5, 5],
       [5, 1, 1, 3, 6, 7, 2],
       [5, 5, 7, 7, 6, 6, 3],
       [7, 2, 6, 7, 4, 7, 7]])

In [39]:
#filter the data in an array                          
a3>4

array([[False, False,  True,  True, False,  True, False],
       [False,  True, False, False,  True,  True,  True],
       [ True, False, False, False,  True,  True, False],
       [ True,  True,  True,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True,  True]])

In [40]:
a3[a3>4]

array([6, 6, 7, 6, 5, 5, 5, 5, 6, 7, 5, 5, 7, 7, 6, 6, 7, 6, 7, 7, 7])

In [42]:
a2

array([[3, 3, 2, 2],
       [6, 3, 6, 2],
       [1, 2, 4, 7]])

In [43]:
#when we want to extract the elements 3,3 that are located in first row
a2[0,[0,1]]

array([3, 3])

In [49]:
a2[1:3,[1,2]]

array([[3, 6],
       [2, 4]])

In [48]:
a2[1:3,[1,2,3]]

array([[3, 6, 2],
       [2, 4, 7]])

In [50]:
a4=np.random.randint(1,3,(3,3))
a5=np.random.randint(1,3,(3,3))

In [51]:
a4

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [52]:
a5

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [53]:
#addition of two arrays by indexes
a4+a5

array([[3, 3, 4],
       [2, 3, 3],
       [3, 2, 3]])

In [54]:
a4-a5

array([[-1, -1,  0],
       [ 0, -1, -1],
       [ 1,  0, -1]])

In [55]:
#it is index wise multiflication not matrix multiflication 
a4*a5

array([[2, 2, 4],
       [1, 2, 2],
       [2, 1, 2]])

In [56]:
#t matrix multiflication 
a4@a5

array([[5, 6, 8],
       [4, 5, 6],
       [6, 7, 8]])

In [57]:
#index wise division
a4/a5

array([[0.5, 0.5, 1. ],
       [1. , 0.5, 0.5],
       [2. , 1. , 0.5]])

In [58]:
a4/0

/tmp/ipykernel_77/3210606993.py:1: RuntimeWarning: divide by zero encountered in divide
  a4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [59]:
#numpy brodcast

In [62]:
a6=np.zeros((3,4))

In [63]:
a6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
a6+7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [65]:
a7=np.array([1,2,3,4])

In [68]:
a7=a6+a7
a7

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [71]:
b=np.array([3,4,5])

In [72]:
a7+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [ ]:
b=np.array([[3,4,5]])

In [73]:
#to bodcast the above we can rotate the array
a7+b.T

array([[4., 5., 6., 7.],
       [5., 6., 7., 8.],
       [6., 7., 8., 9.]])

In [74]:
b1=a7+b.T

In [75]:
#square root of each value
np.sqrt(b1)

array([[2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [76]:
#log of each value
np.log(b1)

array([[1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458]])

In [77]:
#exponent of each value
np.exp(b1)

array([[  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843],
       [ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704],
       [ 403.42879349, 1096.63315843, 2980.95798704, 8103.08392758]])

In [78]:
#minimum value in array
np.min(b1)

4.0

In [ ]:
#numpy part3

In [ ]:
#numy array manipulation

In [12]:
arr=np.random.randint(1,10,(4,4))

In [13]:
arr

array([[7, 7, 7, 1],
       [2, 9, 4, 8],
       [5, 2, 2, 7],
       [6, 9, 2, 8]])

In [15]:
arr.reshape((8,2))

array([[7, 7],
       [7, 1],
       [2, 9],
       [4, 8],
       [5, 2],
       [2, 7],
       [6, 9],
       [2, 8]])

In [16]:
arr.T

array([[7, 2, 5, 6],
       [7, 9, 2, 9],
       [7, 4, 2, 2],
       [1, 8, 7, 8]])

In [17]:
#it will create the one dimensional array
arr.flatten()

array([7, 7, 7, 1, 2, 9, 4, 8, 5, 2, 2, 7, 6, 9, 2, 8])

In [18]:
arr

array([[7, 7, 7, 1],
       [2, 9, 4, 8],
       [5, 2, 2, 7],
       [6, 9, 2, 8]])

In [19]:
np.expand_dims(arr)

TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'

In [20]:
#it will expand the dimension 2d in an array to 3d in column
np.expand_dims(arr,axis=1)

array([[[7, 7, 7, 1]],

       [[2, 9, 4, 8]],

       [[5, 2, 2, 7]],

       [[6, 9, 2, 8]]])

In [21]:
#it will expand the dimension 2d in an array to 3d in row
np.expand_dims(arr,axis=0)

array([[[7, 7, 7, 1],
        [2, 9, 4, 8],
        [5, 2, 2, 7],
        [6, 9, 2, 8]]])

In [25]:
data=np.array([[1],[2],[3],[4]])
data

array([[1],
       [2],
       [3],
       [4]])

In [24]:
#it will squeze the data in nested list which means 2d array to 1d array

np.squeeze(data)

array([1, 2, 3, 4])

In [26]:
data

array([[1],
       [2],
       [3],
       [4]])

In [30]:
#it will repeat one by one element given times in 1d format
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [34]:
#it rotated the array clockwise with given values
np.roll(data,1)

array([[4],
       [1],
       [2],
       [3]])

In [35]:
np.roll(data,2)

array([[3],
       [4],
       [1],
       [2]])

In [36]:
#this function place the given array elements in diagonal and put zeroes to other values
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#numpy-binary operations

In [37]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [38]:
arr1

array([[3, 4, 9],
       [1, 5, 5],
       [6, 6, 3]])

In [39]:
arr2

array([[1, 2, 5],
       [4, 3, 1],
       [5, 8, 2]])

In [40]:
#indexwise addition
arr1+arr2

array([[ 4,  6, 14],
       [ 5,  8,  6],
       [11, 14,  5]])

In [41]:
#indexwise substraction
arr1-arr2

array([[ 2,  2,  4],
       [-3,  2,  4],
       [ 1, -2,  1]])

In [42]:
#indexwise multiflicatin
arr1*arr2

array([[ 3,  8, 45],
       [ 4, 15,  5],
       [30, 48,  6]])

In [43]:
#indexwise division
arr1/arr2

array([[3.        , 2.        , 1.8       ],
       [0.25      , 1.66666667, 5.        ],
       [1.2       , 0.75      , 1.5       ]])

In [44]:
#indexwise power operation
arr1**arr2

array([[      3,      16,   59049],
       [      1,     125,       5],
       [   7776, 1679616,       9]])

In [45]:
#negation of array
~arr1

array([[ -4,  -5, -10],
       [ -2,  -6,  -6],
       [ -7,  -7,  -4]])

In [46]:
arr1>arr2

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [47]:
#numpy string operation

In [48]:
a=np.array(['sudh','kumar'])

In [49]:
#U5-string type in numpy
a

array(['sudh', 'kumar'], dtype='<U5')

In [50]:
#we can perform any string method using char class in numpy
np.char.upper(a)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [51]:
np.char.lower(a)

array(['sudh', 'kumar'], dtype='<U5')

In [52]:
np.char.capitalize(a)

array(['Sudh', 'Kumar'], dtype='<U5')

In [53]:
np.char.islower(a)

array([ True,  True])

In [54]:
np.char.isupper(a)

array([False, False])

In [56]:
np.char.title(a)

array(['Sudh', 'Kumar'], dtype='<U5')

In [57]:
a=np.array(['sudh is','kumar'])

In [58]:
np.char.title(a)

array(['Sudh Is', 'Kumar'], dtype='<U7')

In [59]:
np.char.capitalize(a)

array(['Sudh is', 'Kumar'], dtype='<U7')

In [60]:
arr1

array([[3, 4, 9],
       [1, 5, 5],
       [6, 6, 3]])

In [ ]:
#numpy mathematical function

In [61]:
#sinsodial values
np.sin(arr1)

array([[ 0.14112001, -0.7568025 ,  0.41211849],
       [ 0.84147098, -0.95892427, -0.95892427],
       [-0.2794155 , -0.2794155 ,  0.14112001]])

In [62]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362, -0.91113026],
       [ 0.54030231,  0.28366219,  0.28366219],
       [ 0.96017029,  0.96017029, -0.9899925 ]])

In [63]:
np.tan(arr1)

array([[-0.14254654,  1.15782128, -0.45231566],
       [ 1.55740772, -3.38051501, -3.38051501],
       [-0.29100619, -0.29100619, -0.14254654]])

In [64]:
#logirethemic values of each values in row
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.95424251],
       [0.        , 0.69897   , 0.69897   ],
       [0.77815125, 0.77815125, 0.47712125]])

In [65]:
#exponential values of each values in row
np.exp(arr1)

array([[2.00855369e+01, 5.45981500e+01, 8.10308393e+03],
       [2.71828183e+00, 1.48413159e+02, 1.48413159e+02],
       [4.03428793e+02, 4.03428793e+02, 2.00855369e+01]])

In [67]:
#values power 3 
np.power(arr1,3)

array([[ 27,  64, 729],
       [  1, 125, 125],
       [216, 216,  27]])

In [ ]:
#statistical functions

In [68]:
#mean of whole array
np.mean(arr)

5.375

In [70]:
#median of array
np.median(arr)

6.5

In [74]:
np.std(arr)

2.7128168017763383

In [77]:
np.var(arr)

7.359375

In [75]:
np.max(arr)

9

In [76]:
np.min(arr)

1

In [ ]:
#arithematic functions

In [78]:
arr1

array([[3, 4, 9],
       [1, 5, 5],
       [6, 6, 3]])

In [79]:
arr2

array([[1, 2, 5],
       [4, 3, 1],
       [5, 8, 2]])

In [81]:
arr1-arr2

array([[ 2,  2,  4],
       [-3,  2,  4],
       [ 1, -2,  1]])

In [83]:
#it behaves same as above subtract method but it is built in
np.subtract(arr1,arr2)

array([[ 2,  2,  4],
       [-3,  2,  4],
       [ 1, -2,  1]])

In [85]:
#it behaves same as above addition method but it is built in
np.add(arr1,arr2)

array([[ 4,  6, 14],
       [ 5,  8,  6],
       [11, 14,  5]])

In [86]:
#it multiplies index wise
np.multiply(arr1,arr2)

array([[ 3,  8, 45],
       [ 4, 15,  5],
       [30, 48,  6]])

In [87]:
#it dividesindex wise
np.divide(arr1,arr2)

array([[3.        , 2.        , 1.8       ],
       [0.25      , 1.66666667, 5.        ],
       [1.2       , 0.75      , 1.5       ]])

In [88]:
#it perform modular division of arr1%arr2 and gives remainder
np.mod(arr1,arr2)

array([[0, 0, 4],
       [1, 2, 0],
       [1, 6, 1]])

In [89]:
#it perform arr1**arr2
np.power(arr1,arr2)

array([[      3,      16,   59049],
       [      1,     125,       5],
       [   7776, 1679616,       9]])

In [ ]:
#numpy part 4

In [91]:
#sort,search,count

In [2]:
a=np.array([4,9,2,1,5,7,8,3,10,6,12])

In [97]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [108]:
#Find indices where elements should be inserted to maintain order.
#11 is not in array if we want to add 11 into array it will search and sort and give right index to add element
np.searchsorted(a,11)

10

In [9]:
a2=np.array([0,0,2,6,0,7,8])

In [110]:
#it will tell the number of non zeroes in an array
np.count_nonzero(a2)

4

In [10]:
#it tells what are the indexes which are grater han 0
np.where(a2>0)

(array([2, 3, 5, 6]),)

In [7]:
np.where(a>5)

(array([ 1,  5,  6,  8,  9, 10]),)

In [12]:
a

array([ 4,  9,  2,  1,  5,  7,  8,  3, 10,  6, 12])

In [8]:
np.where(a<5)

(array([0, 2, 3, 7]),)

In [13]:
a

array([ 4,  9,  2,  1,  5,  7,  8,  3, 10,  6, 12])

In [14]:
#it is used to extract the elements from array based some condition
np.extract(a>5,a)

array([ 9,  7,  8, 10,  6, 12])

In [15]:
#numpy-byte swapping-represent the data that are stored in system in bytes=swap original data to bytes

In [16]:
a

array([ 4,  9,  2,  1,  5,  7,  8,  3, 10,  6, 12])

In [19]:
a.byteswap(inplace=True)

array([288230376151711744, 648518346341351424, 144115188075855872,
        72057594037927936, 360287970189639680, 504403158265495552,
       576460752303423488, 216172782113783808, 720575940379279360,
       432345564227567616, 864691128455135232])

In [20]:
#numpy copies and views

In [21]:
#deep copy

In [22]:
a2

array([0, 0, 2, 6, 0, 7, 8])

In [23]:
a3=np.copy(a2)

In [24]:
a3

array([0, 0, 2, 6, 0, 7, 8])

In [25]:
#views==shallw copy

In [26]:
b=a2.view()

In [27]:
b

array([0, 0, 2, 6, 0, 7, 8])

In [28]:
b[0]=200

In [29]:
b

array([200,   0,   2,   6,   0,   7,   8])

In [30]:
a2

array([200,   0,   2,   6,   0,   7,   8])

In [31]:
#numpy-matlib-matrix library

In [32]:
import numpy.matlib as nm

In [34]:
nm.zeros(6)

matrix([[0., 0., 0., 0., 0., 0.]])

In [35]:
nm.ones((5,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
#numpy-linear algebra

In [38]:
arr1=np.random.randint([[2,3],[4,5]])

In [39]:
arr2=np.random.randint([[6,3],[7,5]])

In [40]:
arr1

array([[0, 2],
       [2, 3]])

In [41]:
arr2

array([[3, 1],
       [6, 0]])

In [42]:
np.dot(arr1,arr2)

array([[12,  0],
       [24,  2]])

In [43]:
arr1@arr2

array([[12,  0],
       [24,  2]])